//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeon100Steps.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Armors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Armors() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeon100Steps.Core.Resources.Armors", typeof(Armors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bronze Bracers.
        /// </summary>
        public static string COMMON_BRONZEBRACERS {
            get {
                return ResourceManager.GetString("COMMON_BRONZEBRACERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chainmail Coif.
        /// </summary>
        public static string COMMON_CHAINMAILCOIF {
            get {
                return ResourceManager.GetString("COMMON_CHAINMAILCOIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guard Armour.
        /// </summary>
        public static string COMMON_GUARDARMOUR {
            get {
                return ResourceManager.GetString("COMMON_GUARDARMOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Iron Helmet.
        /// </summary>
        public static string COMMON_IRONHELMET {
            get {
                return ResourceManager.GetString("COMMON_IRONHELMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leather Vest.
        /// </summary>
        public static string COMMON_LEATHERVEST {
            get {
                return ResourceManager.GetString("COMMON_LEATHERVEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light Shield.
        /// </summary>
        public static string COMMON_LIGHTSHIELD {
            get {
                return ResourceManager.GetString("COMMON_LIGHTSHIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Padded Jacket.
        /// </summary>
        public static string COMMON_PADDEDJACKET {
            get {
                return ResourceManager.GetString("COMMON_PADDEDJACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reinforced Gloves.
        /// </summary>
        public static string COMMON_REINFORCEDGLOVES {
            get {
                return ResourceManager.GetString("COMMON_REINFORCEDGLOVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soldier Boots.
        /// </summary>
        public static string COMMON_SOLDIERBOOTS {
            get {
                return ResourceManager.GetString("COMMON_SOLDIERBOOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studded Belt.
        /// </summary>
        public static string COMMON_STUDDEDBELT {
            get {
                return ResourceManager.GetString("COMMON_STUDDEDBELT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linen Shirt.
        /// </summary>
        public static string DEFAULTARMOR {
            get {
                return ResourceManager.GetString("DEFAULTARMOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aether Plate.
        /// </summary>
        public static string ELITE_AETHERPLATE {
            get {
                return ResourceManager.GetString("ELITE_AETHERPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phoenix Embrace.
        /// </summary>
        public static string ELITE_PHOENIXEMBRACE {
            get {
                return ResourceManager.GetString("ELITE_PHOENIXEMBRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Void Stalker Garb.
        /// </summary>
        public static string ELITE_VOIDSTALKERGARB {
            get {
                return ResourceManager.GetString("ELITE_VOIDSTALKERGARB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Broken Chainmail.
        /// </summary>
        public static string JUNK_BROKENCHAINMAIL {
            get {
                return ResourceManager.GetString("JUNK_BROKENCHAINMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cracked Buckler.
        /// </summary>
        public static string JUNK_CRACKEDBUCKLER {
            get {
                return ResourceManager.GetString("JUNK_CRACKEDBUCKLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dirty Cloak.
        /// </summary>
        public static string JUNK_DIRTYCLOAK {
            get {
                return ResourceManager.GetString("JUNK_DIRTYCLOAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Improvised Helmet.
        /// </summary>
        public static string JUNK_IMPROVISEDHELMET {
            get {
                return ResourceManager.GetString("JUNK_IMPROVISEDHELMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moldy Leather.
        /// </summary>
        public static string JUNK_MOLDYLEATHER {
            get {
                return ResourceManager.GetString("JUNK_MOLDYLEATHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Patched Pants.
        /// </summary>
        public static string JUNK_PATCHEDPANTS {
            get {
                return ResourceManager.GetString("JUNK_PATCHEDPANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotten Wood Shield.
        /// </summary>
        public static string JUNK_ROTTENWOODSHIELD {
            get {
                return ResourceManager.GetString("JUNK_ROTTENWOODSHIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rusty Chestplate.
        /// </summary>
        public static string JUNK_RUSTYCHESTPLATE {
            get {
                return ResourceManager.GetString("JUNK_RUSTYCHESTPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tattered Cloth.
        /// </summary>
        public static string JUNK_TATTEREDCLOTH {
            get {
                return ResourceManager.GetString("JUNK_TATTEREDCLOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thin Rags.
        /// </summary>
        public static string JUNK_THINRAGS {
            get {
                return ResourceManager.GetString("JUNK_THINRAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Celestial Crown.
        /// </summary>
        public static string RARE_CELESTIALCROWN {
            get {
                return ResourceManager.GetString("RARE_CELESTIALCROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dragon Scale Shield.
        /// </summary>
        public static string RARE_DRAGONSCALESHIELD {
            get {
                return ResourceManager.GetString("RARE_DRAGONSCALESHIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enchanted Robe.
        /// </summary>
        public static string RARE_ENCHANTEDROBE {
            get {
                return ResourceManager.GetString("RARE_ENCHANTEDROBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mithril Chainmail.
        /// </summary>
        public static string RARE_MITHRILCHAINMAIL {
            get {
                return ResourceManager.GetString("RARE_MITHRILCHAINMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hardened Leather.
        /// </summary>
        public static string UNCOMMON_HARDENEDLEATHER {
            get {
                return ResourceManager.GetString("UNCOMMON_HARDENEDLEATHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Knight Gauntlets.
        /// </summary>
        public static string UNCOMMON_KNIGHTGAUNTLETS {
            get {
                return ResourceManager.GetString("UNCOMMON_KNIGHTGAUNTLETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scout Cloak.
        /// </summary>
        public static string UNCOMMON_SCOUTCLOAK {
            get {
                return ResourceManager.GetString("UNCOMMON_SCOUTCLOAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Steel Breastplate.
        /// </summary>
        public static string UNCOMMON_STEELBREASTPLATE {
            get {
                return ResourceManager.GetString("UNCOMMON_STEELBREASTPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veteran Helmet.
        /// </summary>
        public static string UNCOMMON_VETERANHELMET {
            get {
                return ResourceManager.GetString("UNCOMMON_VETERANHELMET", resourceCulture);
            }
        }
    }
}
