//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeon100Steps.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bonus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bonus() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeon100Steps.Core.Resources.Bonus", typeof(Bonus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AttackAmount: {0}.
        /// </summary>
        public static string BONUS_ATTACK {
            get {
                return ResourceManager.GetString("BONUS_ATTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The enemy bleed and lose {0} life points on {1} turns.
        /// </summary>
        public static string BONUS_BLEED {
            get {
                return ResourceManager.GetString("BONUS_BLEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Defense: {0}.
        /// </summary>
        public static string BONUS_DEFENSE {
            get {
                return ResourceManager.GetString("BONUS_DEFENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inflict {0} Fire Damage per attack for {1} turn.
        /// </summary>
        public static string BONUS_FIRE {
            get {
                return ResourceManager.GetString("BONUS_FIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recover {0} Life Points per attack.
        /// </summary>
        public static string BONUS_HEALTH {
            get {
                return ResourceManager.GetString("BONUS_HEALTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inflict {0} Ice Damage per attack.
        /// </summary>
        public static string BONUS_ICE {
            get {
                return ResourceManager.GetString("BONUS_ICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recover {0} Mana per attack.
        /// </summary>
        public static string BONUS_MANA {
            get {
                return ResourceManager.GetString("BONUS_MANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inflict {0} poison damages on {1} turns.
        /// </summary>
        public static string BONUS_POISON {
            get {
                return ResourceManager.GetString("BONUS_POISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bleed Resistance: {0}%.
        /// </summary>
        public static string BONUS_RESISTBLEED {
            get {
                return ResourceManager.GetString("BONUS_RESISTBLEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fire Resistance: {0}%.
        /// </summary>
        public static string BONUS_RESISTFIRE {
            get {
                return ResourceManager.GetString("BONUS_RESISTFIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ice Resistance: {0}%.
        /// </summary>
        public static string BONUS_RESISTICE {
            get {
                return ResourceManager.GetString("BONUS_RESISTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poison Resistance: {0}%.
        /// </summary>
        public static string BONUS_RESISTPOISON {
            get {
                return ResourceManager.GetString("BONUS_RESISTPOISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stunt Resistance: {0}%.
        /// </summary>
        public static string BONUS_RESISTSTUNT {
            get {
                return ResourceManager.GetString("BONUS_RESISTSTUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stunt the enemy for {0} turns.
        /// </summary>
        public static string BONUS_STUNT {
            get {
                return ResourceManager.GetString("BONUS_STUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lose {0} points of life per attack.
        /// </summary>
        public static string MALUS_HEALTH {
            get {
                return ResourceManager.GetString("MALUS_HEALTH", resourceCulture);
            }
        }
    }
}
