//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeon100Steps.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeon100Steps.Core.Resources.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As you run, you trigger the trap and several arrows tear into your skin..
        /// </summary>
        public static string TRAP_DART_ACTIVATED {
            get {
                return ResourceManager.GetString("TRAP_DART_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à While disarming the trap, you lose your balance and fall onto an arrowhead, which pierces you..
        /// </summary>
        public static string TRAP_DART_DISARM_FAILED {
            get {
                return ResourceManager.GetString("TRAP_DART_DISARM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As you bend down to examine the tile in front of you, you notice a reflection on one of the trap&apos;s arrowheads..
        /// </summary>
        public static string TRAP_DART_DISARM_SUCCESS {
            get {
                return ResourceManager.GetString("TRAP_DART_DISARM_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You walk into the room and something doesn&apos;t seem right..
        /// </summary>
        public static string TRAP_DEFAULT {
            get {
                return ResourceManager.GetString("TRAP_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You&apos;ll run like crazy to the other side of the room.
        ///That&apos;s all..
        /// </summary>
        public static string TRAP_NONE_ACTIVATED {
            get {
                return ResourceManager.GetString("TRAP_NONE_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You worked on the trap for several minutes without any effect... Which is normal, because there was no trap!.
        /// </summary>
        public static string TRAP_NONE_DISARM_FAILED {
            get {
                return ResourceManager.GetString("TRAP_NONE_DISARM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You quickly ease your doubts and realize that there is no trap..
        /// </summary>
        public static string TRAP_NONE_DISARM_SUCCESS {
            get {
                return ResourceManager.GetString("TRAP_NONE_DISARM_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You feel the ground giving way beneath your feet as you run. You are knocked breathless by the impact against the edge of the hole, which you cling to with all your strength..
        /// </summary>
        public static string TRAP_PIT_ACTIVATED {
            get {
                return ResourceManager.GetString("TRAP_PIT_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As soon as you start to inspect the next tile, you lose your balance and fall forward, landing on a large rock at the bottom of the hole..
        /// </summary>
        public static string TRAP_PIT_DISARM_FAILED {
            get {
                return ResourceManager.GetString("TRAP_PIT_DISARM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You notice that the tile in front of you is slightly raised in one corner. You walk around the tile and continue on your way..
        /// </summary>
        public static string TRAP_PIT_DISARM_SUCCESS {
            get {
                return ResourceManager.GetString("TRAP_PIT_DISARM_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A sickening fume rises from the ground and you start coughing and crying..
        /// </summary>
        public static string TRAP_POISON_ACTIVATED {
            get {
                return ResourceManager.GetString("TRAP_POISON_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à While searching for the trap&apos;s trigger, you stumble upon one of the trap&apos;s gas pockets... which you accidentally puncture..
        /// </summary>
        public static string TRAP_POISON_DISARM_FAILED {
            get {
                return ResourceManager.GetString("TRAP_POISON_DISARM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à During your inspection, you notice several small holes around you. You quickly hold your breath and cover your mouth and nose with a cloth..
        /// </summary>
        public static string TRAP_POISON_DISARM_SUCCESS {
            get {
                return ResourceManager.GetString("TRAP_POISON_DISARM_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As soon as you start running, a flurry of rubble falls on you..
        /// </summary>
        public static string TRAP_PRESSUREPLATE_ACTIVATED {
            get {
                return ResourceManager.GetString("TRAP_PRESSUREPLATE_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You move cautiously through the room when you feel something like sand slipping into your neck, and as soon as you look up, a large rock falls on you..
        /// </summary>
        public static string TRAP_PRESSUREPLATE_DISARM_FAILED {
            get {
                return ResourceManager.GetString("TRAP_PRESSUREPLATE_DISARM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You spot some sand on the ground. You take a detour to avoid ending up under the affected area..
        /// </summary>
        public static string TRAP_PRESSUREPLATE_DISARM_SUCCESS {
            get {
                return ResourceManager.GetString("TRAP_PRESSUREPLATE_DISARM_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You take {0} damage..
        /// </summary>
        public static string TRAP_RECEIVE_DAMAGE {
            get {
                return ResourceManager.GetString("TRAP_RECEIVE_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You prefer to run away from the dungeon...
        ///Coward..
        /// </summary>
        public static string TRAP_RUN_AWAY {
            get {
                return ResourceManager.GetString("TRAP_RUN_AWAY", resourceCulture);
            }
        }
    }
}
