//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeon100Steps.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menus() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeon100Steps.Core.Resources.Menus", typeof(Menus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string GAME_FIRST_EVENT {
            get {
                return ResourceManager.GetString("GAME_FIRST_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next room.
        /// </summary>
        public static string GAME_NEXT_EVENT {
            get {
                return ResourceManager.GetString("GAME_NEXT_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PROGRESSION.
        /// </summary>
        public static string GAME_PROGRESSION {
            get {
                return ResourceManager.GetString("GAME_PROGRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dungeon 100 Steps.
        /// </summary>
        public static string GAME_TITLE {
            get {
                return ResourceManager.GetString("GAME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drink.
        /// </summary>
        public static string INVENTORY_DRINK {
            get {
                return ResourceManager.GetString("INVENTORY_DRINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drop.
        /// </summary>
        public static string INVENTORY_DROP {
            get {
                return ResourceManager.GetString("INVENTORY_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equip.
        /// </summary>
        public static string INVENTORY_EQUIP {
            get {
                return ResourceManager.GetString("INVENTORY_EQUIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a touch of sparkle to armors....
        /// </summary>
        public static string LOADING_ARMORS {
            get {
                return ResourceManager.GetString("LOADING_ARMORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emptying the bags....
        /// </summary>
        public static string LOADING_BAGS {
            get {
                return ResourceManager.GetString("LOADING_BAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Potions making underway....
        /// </summary>
        public static string LOADING_POTIONS {
            get {
                return ResourceManager.GetString("LOADING_POTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weapons Sharpening in Progress....
        /// </summary>
        public static string LOADING_WEAPONS {
            get {
                return ResourceManager.GetString("LOADING_WEAPONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wizardess.
        /// </summary>
        public static string MAGE_FEMALE {
            get {
                return ResourceManager.GetString("MAGE_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wizard.
        /// </summary>
        public static string MAGE_MALE {
            get {
                return ResourceManager.GetString("MAGE_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        public static string MAINMENU_CONTINUE {
            get {
                return ResourceManager.GetString("MAINMENU_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string MAINMENU_OPTIONS {
            get {
                return ResourceManager.GetString("MAINMENU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        public static string MAINMENU_PLAY {
            get {
                return ResourceManager.GetString("MAINMENU_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string MAINMENU_QUIT {
            get {
                return ResourceManager.GetString("MAINMENU_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Audio.
        /// </summary>
        public static string OPTIONS_CATEGORY_AUDIO {
            get {
                return ResourceManager.GetString("OPTIONS_CATEGORY_AUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Controls.
        /// </summary>
        public static string OPTIONS_CATEGORY_CONTROLS {
            get {
                return ResourceManager.GetString("OPTIONS_CATEGORY_CONTROLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Graphics.
        /// </summary>
        public static string OPTIONS_CATEGORY_GRAPHICS {
            get {
                return ResourceManager.GetString("OPTIONS_CATEGORY_GRAPHICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fullscreen.
        /// </summary>
        public static string OPTIONS_LBL_FULLSCREEN {
            get {
                return ResourceManager.GetString("OPTIONS_LBL_FULLSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Master Volume.
        /// </summary>
        public static string OPTIONS_LBL_MASTERVOLUME {
            get {
                return ResourceManager.GetString("OPTIONS_LBL_MASTERVOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music Volume.
        /// </summary>
        public static string OPTIONS_LBL_MUSICVOLUME {
            get {
                return ResourceManager.GetString("OPTIONS_LBL_MUSICVOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resolution.
        /// </summary>
        public static string OPTIONS_LBL_RESOLUTION {
            get {
                return ResourceManager.GetString("OPTIONS_LBL_RESOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SFX Volume.
        /// </summary>
        public static string OPTIONS_LBL_SOUNDSVOLUME {
            get {
                return ResourceManager.GetString("OPTIONS_LBL_SOUNDSVOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string OPTIONS_TITLE {
            get {
                return ResourceManager.GetString("OPTIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        public static string PAUSE_TITLE {
            get {
                return ResourceManager.GetString("PAUSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AttackAmount:.
        /// </summary>
        public static string PLAYER_ATTACK_LABEL {
            get {
                return ResourceManager.GetString("PLAYER_ATTACK_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class:.
        /// </summary>
        public static string PLAYER_CLASS_LABEL {
            get {
                return ResourceManager.GetString("PLAYER_CLASS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Defense:.
        /// </summary>
        public static string PLAYER_DEFENSE_LABEL {
            get {
                return ResourceManager.GetString("PLAYER_DEFENSE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gold:.
        /// </summary>
        public static string PLAYER_GOLD_LABEL {
            get {
                return ResourceManager.GetString("PLAYER_GOLD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Health:.
        /// </summary>
        public static string PLAYER_HEALTH_LABEL {
            get {
                return ResourceManager.GetString("PLAYER_HEALTH_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mana:.
        /// </summary>
        public static string PLAYER_MANA_LABEL {
            get {
                return ResourceManager.GetString("PLAYER_MANA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press a key/button to continue.
        /// </summary>
        public static string PRESS_TO_CONTINUE {
            get {
                return ResourceManager.GetString("PRESS_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string SELECTIONPLAYER_BACK {
            get {
                return ResourceManager.GetString("SELECTIONPLAYER_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Female.
        /// </summary>
        public static string SELECTIONPLAYER_FEMALE {
            get {
                return ResourceManager.GetString("SELECTIONPLAYER_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Male.
        /// </summary>
        public static string SELECTIONPLAYER_MALE {
            get {
                return ResourceManager.GetString("SELECTIONPLAYER_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        public static string SELECTIONPLAYER_NEXT {
            get {
                return ResourceManager.GetString("SELECTIONPLAYER_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thief.
        /// </summary>
        public static string THIEF_FEMALE {
            get {
                return ResourceManager.GetString("THIEF_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thief.
        /// </summary>
        public static string THIEF_MALE {
            get {
                return ResourceManager.GetString("THIEF_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Would you like to start the tutorial?.
        /// </summary>
        public static string TUTORIALSKIP_MESSAGE {
            get {
                return ResourceManager.GetString("TUTORIALSKIP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string TUTORIALSKIP_NO {
            get {
                return ResourceManager.GetString("TUTORIALSKIP_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string TUTORIALSKIP_YES {
            get {
                return ResourceManager.GetString("TUTORIALSKIP_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        public static string UI_APPLY {
            get {
                return ResourceManager.GetString("UI_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string UI_BACK {
            get {
                return ResourceManager.GetString("UI_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        public static string UI_RESET {
            get {
                return ResourceManager.GetString("UI_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warrior.
        /// </summary>
        public static string WARRIOR_FEMALE {
            get {
                return ResourceManager.GetString("WARRIOR_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warrior.
        /// </summary>
        public static string WARRIOR_MALE {
            get {
                return ResourceManager.GetString("WARRIOR_MALE", resourceCulture);
            }
        }
    }
}
