//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeon100Steps.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Weapons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Weapons() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeon100Steps.Core.Resources.Weapons", typeof(Weapons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basic Morningstar.
        /// </summary>
        public static string COMMON_BASICMORNINGSTAR {
            get {
                return ResourceManager.GetString("COMMON_BASICMORNINGSTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guard&apos;s Spear.
        /// </summary>
        public static string COMMON_GUARDSPEAR {
            get {
                return ResourceManager.GetString("COMMON_GUARDSPEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hunting Longbow.
        /// </summary>
        public static string COMMON_HUNTINGLONGBOW {
            get {
                return ResourceManager.GetString("COMMON_HUNTINGLONGBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infantry Pike.
        /// </summary>
        public static string COMMON_INFANTRYPIKE {
            get {
                return ResourceManager.GetString("COMMON_INFANTRYPIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Iron Gladius.
        /// </summary>
        public static string COMMON_IRONGLADIUS {
            get {
                return ResourceManager.GetString("COMMON_IRONGLADIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Iron-shod Staff.
        /// </summary>
        public static string COMMON_IRONSHODSTAFF {
            get {
                return ResourceManager.GetString("COMMON_IRONSHODSTAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light Rapier.
        /// </summary>
        public static string COMMON_LIGHTRAPIER {
            get {
                return ResourceManager.GetString("COMMON_LIGHTRAPIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Militia Shortsword.
        /// </summary>
        public static string COMMON_MILITIASHORTSWORD {
            get {
                return ResourceManager.GetString("COMMON_MILITIASHORTSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nomad Scimitar.
        /// </summary>
        public static string COMMON_NOMADSCIMITAR {
            get {
                return ResourceManager.GetString("COMMON_NOMADSCIMITAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Peasant&apos;s Billhook.
        /// </summary>
        public static string COMMON_PEASANTBILLHOOK {
            get {
                return ResourceManager.GetString("COMMON_PEASANTBILLHOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Precision Sling.
        /// </summary>
        public static string COMMON_PRECISIONSLING {
            get {
                return ResourceManager.GetString("COMMON_PRECISIONSLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sailor&apos;s Cutlass.
        /// </summary>
        public static string COMMON_SAILORCUTLASS {
            get {
                return ResourceManager.GetString("COMMON_SAILORCUTLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simple Mace.
        /// </summary>
        public static string COMMON_SIMPLEMACE {
            get {
                return ResourceManager.GetString("COMMON_SIMPLEMACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smithing Hammer.
        /// </summary>
        public static string COMMON_SMITHINGHAMMER {
            get {
                return ResourceManager.GetString("COMMON_SMITHINGHAMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spiked Club.
        /// </summary>
        public static string COMMON_SPIKEDCLUB {
            get {
                return ResourceManager.GetString("COMMON_SPIKEDCLUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Steel Dagger.
        /// </summary>
        public static string COMMON_STEELDAGGER {
            get {
                return ResourceManager.GetString("COMMON_STEELDAGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Throwing Hatchet.
        /// </summary>
        public static string COMMON_THROWINGHATCHET {
            get {
                return ResourceManager.GetString("COMMON_THROWINGHATCHET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Woodman&apos;s Axe.
        /// </summary>
        public static string COMMON_WOODMANAXE {
            get {
                return ResourceManager.GetString("COMMON_WOODMANAXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Worn Bastard Sword.
        /// </summary>
        public static string COMMON_WORNBASTARDSWORD {
            get {
                return ResourceManager.GetString("COMMON_WORNBASTARDSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yew Shortbow.
        /// </summary>
        public static string COMMON_YEWSHORTBOW {
            get {
                return ResourceManager.GetString("COMMON_YEWSHORTBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bare Hands.
        /// </summary>
        public static string DEFAULTWEAPON {
            get {
                return ResourceManager.GetString("DEFAULTWEAPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Agonizer.
        /// </summary>
        public static string ELITE_AGONIZER {
            get {
                return ResourceManager.GetString("ELITE_AGONIZER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doomsday.
        /// </summary>
        public static string ELITE_DOOMSDAY {
            get {
                return ResourceManager.GetString("ELITE_DOOMSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dragon&apos;s Breath.
        /// </summary>
        public static string ELITE_DRAGONBREATH {
            get {
                return ResourceManager.GetString("ELITE_DRAGONBREATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eclipse Shard.
        /// </summary>
        public static string ELITE_ECLIPSESHARD {
            get {
                return ResourceManager.GetString("ELITE_ECLIPSESHARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mountain Breaker.
        /// </summary>
        public static string ELITE_MOUNTAINBREAKER {
            get {
                return ResourceManager.GetString("ELITE_MOUNTAINBREAKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bend Poker.
        /// </summary>
        public static string JUNK_BENDPOKER {
            get {
                return ResourceManager.GetString("JUNK_BENDPOKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Broken Pickaxe Handle.
        /// </summary>
        public static string JUNK_BROKENPICKAXEHANDLE {
            get {
                return ResourceManager.GetString("JUNK_BROKENPICKAXEHANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dull Kitchen Knife.
        /// </summary>
        public static string JUNK_DULLKITCHENKNIFE {
            get {
                return ResourceManager.GetString("JUNK_DULLKITCHENKNIFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Large Mammal Bone.
        /// </summary>
        public static string JUNK_LARGEMAMMALBONE {
            get {
                return ResourceManager.GetString("JUNK_LARGEMAMMALBONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pot Lid.
        /// </summary>
        public static string JUNK_POTLID {
            get {
                return ResourceManager.GetString("JUNK_POTLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rusty Dagger.
        /// </summary>
        public static string JUNK_RUSTYDAGGER {
            get {
                return ResourceManager.GetString("JUNK_RUSTYDAGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sharpened Branch.
        /// </summary>
        public static string JUNK_SHARPENEDBRANCH {
            get {
                return ResourceManager.GetString("JUNK_SHARPENEDBRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stone Club.
        /// </summary>
        public static string JUNK_STONECLUB {
            get {
                return ResourceManager.GetString("JUNK_STONECLUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wooden Training Sword.
        /// </summary>
        public static string JUNK_WOODENTRAININGSWORD {
            get {
                return ResourceManager.GetString("JUNK_WOODENTRAININGSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Worn Leather Sling.
        /// </summary>
        public static string JUNK_WORNLEATHERSLING {
            get {
                return ResourceManager.GetString("JUNK_WORNLEATHERSLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assassin&apos;s Dirk.
        /// </summary>
        public static string RARE_ASSASSINDIRK {
            get {
                return ResourceManager.GetString("RARE_ASSASSINDIRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ebony Wood Bow.
        /// </summary>
        public static string RARE_EBONYWOODBOW {
            get {
                return ResourceManager.GetString("RARE_EBONYWOODBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fire Flail.
        /// </summary>
        public static string RARE_FIREFLAIL {
            get {
                return ResourceManager.GetString("RARE_FIREFLAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Frost Spear.
        /// </summary>
        public static string RARE_FROSTSPEAR {
            get {
                return ResourceManager.GetString("RARE_FROSTSPEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Glowing Sword of Justice.
        /// </summary>
        public static string RARE_GLOWINGJUSTICESWORD {
            get {
                return ResourceManager.GetString("RARE_GLOWINGJUSTICESWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heavy Siege Crossbow.
        /// </summary>
        public static string RARE_HEAVYSIEGECROSSBOW {
            get {
                return ResourceManager.GetString("RARE_HEAVYSIEGECROSSBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Master&apos;s Katana.
        /// </summary>
        public static string RARE_MASTERKATANA {
            get {
                return ResourceManager.GetString("RARE_MASTERKATANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mithril Blade.
        /// </summary>
        public static string RARE_MITHRILBLADE {
            get {
                return ResourceManager.GetString("RARE_MITHRILBLADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Runic Axe.
        /// </summary>
        public static string RARE_RUNICAXE {
            get {
                return ResourceManager.GetString("RARE_RUNICAXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thunder Hammer.
        /// </summary>
        public static string RARE_THUNDERHANNER {
            get {
                return ResourceManager.GetString("RARE_THUNDERHANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claymore.
        /// </summary>
        public static string UNCOMMON_CLAYMORE {
            get {
                return ResourceManager.GetString("UNCOMMON_CLAYMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Composite Bow.
        /// </summary>
        public static string UNCOMMON_COMPOSITEBOW {
            get {
                return ResourceManager.GetString("UNCOMMON_COMPOSITEBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double-Edged Battle Axe.
        /// </summary>
        public static string UNCOMMON_DOUBLEEDGEDBATTLEAXE {
            get {
                return ResourceManager.GetString("UNCOMMON_DOUBLEEDGEDBATTLEAXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duelist&apos;s Estoc.
        /// </summary>
        public static string UNCOMMON_DUELISTESTOC {
            get {
                return ResourceManager.GetString("UNCOMMON_DUELISTESTOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flail.
        /// </summary>
        public static string UNCOMMON_FLAIL {
            get {
                return ResourceManager.GetString("UNCOMMON_FLAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gladiator&apos;s Trident.
        /// </summary>
        public static string UNCOMMON_GLADIATORTRIDENT {
            get {
                return ResourceManager.GetString("UNCOMMON_GLADIATORTRIDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Great War Hammer.
        /// </summary>
        public static string UNCOMMON_GREATWARHAMMER {
            get {
                return ResourceManager.GetString("UNCOMMON_GREATWARHAMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hand Crossbow.
        /// </summary>
        public static string UNCOMMON_HANDCROSSBOW {
            get {
                return ResourceManager.GetString("UNCOMMON_HANDCROSSBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hardened Steel Longsword.
        /// </summary>
        public static string UNCOMMON_HARDENEDSTEELLONGSWORD {
            get {
                return ResourceManager.GetString("UNCOMMON_HARDENEDSTEELLONGSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Officer&apos;s Spear.
        /// </summary>
        public static string UNCOMMON_OFFICERSPEAR {
            get {
                return ResourceManager.GetString("UNCOMMON_OFFICERSPEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Officer&apos;s Saber.
        /// </summary>
        public static string UNCOMMON_OFFICIERSABER {
            get {
                return ResourceManager.GetString("UNCOMMON_OFFICIERSABER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ranger&apos;s Bow.
        /// </summary>
        public static string UNCOMMON_RANGERBOW {
            get {
                return ResourceManager.GetString("UNCOMMON_RANGERBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reinforced Halberd.
        /// </summary>
        public static string UNCOMMON_REINFORCEDHALBERD {
            get {
                return ResourceManager.GetString("UNCOMMON_REINFORCEDHALBERD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Templar Heavy Mace.
        /// </summary>
        public static string UNCOMMON_TEMPLARHEAVYMACE {
            get {
                return ResourceManager.GetString("UNCOMMON_TEMPLARHEAVYMACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thief&apos;s Dagger.
        /// </summary>
        public static string UNCOMMON_THIEFDAGGER {
            get {
                return ResourceManager.GetString("UNCOMMON_THIEFDAGGER", resourceCulture);
            }
        }
    }
}
